name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild build test -scheme Injected-Package -enableCodeCoverage YES | xcpretty -r junit && exit ${PIPESTATUS[0]}
    - name: Publish code coverage results
      run: bash <(curl -s https://codecov.io/bash)
